// ============================================================
// cards_ccp.js — 中共陣營卡牌資料庫
// 結構同 cards_taiwan.js
// ============================================================

const CCP_CARDS = [

  // ──────────────────────────────────────────────
  // 類別：軍事恫嚇
  // ──────────────────────────────────────────────
  {
    id: 'ccp_mil_exercise',
    name: '圍島軍事演習',
    category: '軍事',
    cost: 2,
    desc: '大規模演習模擬封鎖，製造心理壓力',
    flavor: '「常態化巡邏」是新的正常',
    effects: { military: 8, tension: 10 },
    sideEffects: { tw_morale: -10, tw_economy: -4 },
  },
  {
    id: 'ccp_missile_test',
    name: '飛彈試射',
    category: '軍事',
    cost: 1,
    desc: '向臺灣周邊海域發射彈道飛彈',
    flavor: '1996年的劇本，不斷重演',
    effects: { military: 6, tension: 8 },
    sideEffects: { tw_morale: -8 },
  },
  {
    id: 'ccp_carrier_group',
    name: '航母戰鬥群',
    category: '軍事',
    cost: 3,
    desc: '福建號航母戰鬥群繞台巡弋',
    flavor: '看得見的拳頭才有震懾力',
    effects: { military: 14, tension: 12 },
    sideEffects: { tw_morale: -12, tw_diplomacy: -5 },
    cooldown: 3,
    triggersTW: 'tw_us_alliance',
  },
  {
    id: 'ccp_adiz_violation',
    name: '防空識別區侵擾',
    category: '軍事',
    cost: 1,
    desc: '戰機頻繁越過中線，常態化侵擾',
    flavor: '灰色地帶：不開戰，但也不讓你安寧',
    effects: { military: 5, tension: 6 },
    sideEffects: { tw_morale: -6, tw_intel: -3 },
  },
  {
    id: 'ccp_blockade_drill',
    name: '海上封鎖演練',
    category: '軍事',
    cost: 2,
    desc: '模擬切斷臺灣海上補給線',
    flavor: '孤立一座島，不需要真的打',
    effects: { military: 10, tension: 12 },
    sideEffects: { tw_economy: -8, tw_morale: -8 },
    cooldown: 2,
  },
  {
    id: 'ccp_amphibious_drill',
    name: '兩棲登陸演習',
    category: '軍事',
    cost: 2,
    desc: '在福建沿海演練大規模登陸作戰',
    flavor: '「正常訓練」——官方說法永遠如此',
    effects: { military: 12, tension: 10 },
    sideEffects: { tw_morale: -10 },
    cooldown: 2,
  },
  {
    id: 'ccp_hypersonic',
    name: '高超音速飛彈部署',
    category: '軍事',
    cost: 3,
    desc: '在福建部署DF-17高超音速飛彈',
    flavor: '任何防禦系統都攔截不了',
    effects: { military: 16 },
    sideEffects: { tw_morale: -14, tension: 14 },
    cooldown: 3,
  },
  {
    id: 'ccp_special_ops',
    name: '特種作戰準備',
    category: '軍事',
    cost: 2,
    desc: '滲透特種部隊預置在台，準備斬首行動',
    flavor: '戰爭還沒開始，棋子已在棋盤上',
    effects: { military: 8, infiltration: 8 },
    sideEffects: { tw_intel: -8 },
  },

  // ──────────────────────────────────────────────
  // 類別：政治滲透
  // ──────────────────────────────────────────────
  {
    id: 'ccp_legis_infiltrate',
    name: '立法院內應',
    category: '滲透',
    cost: 2,
    desc: '資助親中立委推動有利法案，刪減國防預算',
    flavor: '最有效的武器是對手的投票機器',
    effects: { infiltration: 12 },
    sideEffects: { tw_military: -10, tw_morale: -5 },
    special: 'infiltrate_legislators',
  },
  {
    id: 'ccp_recruit_officers',
    name: '收買退役將領',
    category: '滲透',
    cost: 2,
    desc: '重金吸收退役高階軍官，竊取軍事機密',
    flavor: '每個退將都是打開金庫的鑰匙',
    effects: { infiltration: 10 },
    sideEffects: { tw_military: -8, tw_intel: -10 },
    special: 'infiltrate_officers',
  },
  {
    id: 'ccp_buy_journalists',
    name: '買通媒體記者',
    category: '滲透',
    cost: 1,
    desc: '以資金滲透媒體，製造親中輿論',
    flavor: '報導角度決定一切',
    effects: { propaganda: 8, infiltration: 6 },
    sideEffects: { tw_morale: -8, tw_resilience: -4 },
    special: 'infiltrate_journalists',
  },
  {
    id: 'ccp_student_spies',
    name: '留學生情蒐',
    category: '滲透',
    cost: 1,
    desc: '在台灣大學佈建情報線人',
    flavor: '學術交流是最好的掩護',
    effects: { infiltration: 8, intel: 6 },
    sideEffects: { tw_intel: -6 },
    special: 'infiltrate_students',
  },
  {
    id: 'ccp_local_faction',
    name: '地方派系滲透',
    category: '滲透',
    cost: 2,
    desc: '透過地方選舉與派系政治滲透基層',
    flavor: '從鄉鎮代表開始，一步一步往上爬',
    effects: { infiltration: 10 },
    sideEffects: { tw_morale: -7, tw_resilience: -5 },
  },
  {
    id: 'ccp_business_capture',
    name: '台商利益收編',
    category: '滲透',
    cost: 1,
    desc: '以在中台商為槓桿，影響台灣商界政治立場',
    flavor: '生意人最怕的是失去市場',
    effects: { infiltration: 7, economy: 4 },
    sideEffects: { tw_economy: -5, tw_diplomacy: -3 },
  },
  {
    id: 'ccp_academic_infiltrate',
    name: '學術交流滲透',
    category: '滲透',
    cost: 1,
    desc: '孔子學院與學術合作作為情蒐管道',
    flavor: '軟的比硬的更難防',
    effects: { infiltration: 6, propaganda: 5 },
    sideEffects: { tw_intel: -4, tw_resilience: -3 },
  },

  // ──────────────────────────────────────────────
  // 類別：認知作戰
  // ──────────────────────────────────────────────
  {
    id: 'ccp_propaganda',
    name: '認知作戰',
    category: '認知',
    cost: 1,
    desc: '大規模社群媒體假訊息，分裂台灣社會',
    flavor: '讓台灣人自己吵，比打仗省力多了',
    effects: { propaganda: 10 },
    sideEffects: { tw_morale: -10, tw_resilience: -5 },
  },
  {
    id: 'ccp_deepfake',
    name: '深偽影片攻勢',
    category: '認知',
    cost: 2,
    desc: '製作政治人物深偽影片，散播恐慌與不信任',
    flavor: 'AI讓謊言變得完美',
    effects: { propaganda: 12 },
    sideEffects: { tw_morale: -12, tw_diplomacy: -4 },
    cooldown: 2,
  },
  {
    id: 'ccp_war_fatigue',
    name: '製造厭戰情緒',
    category: '認知',
    cost: 1,
    desc: '散播「抵抗無用」的悲觀敘事',
    flavor: '最好的征服是讓對方放棄抵抗意志',
    effects: { propaganda: 8 },
    sideEffects: { tw_morale: -14, tw_military: -3 },
  },
  {
    id: 'ccp_fake_news_flood',
    name: '假新聞洪水攻勢',
    category: '認知',
    cost: 1,
    desc: '大量假新聞讓台灣社會真偽難辨',
    flavor: '不需要贏得辯論，只需要讓人迷惑',
    effects: { propaganda: 9 },
    sideEffects: { tw_resilience: -8, tw_morale: -6 },
  },
  {
    id: 'ccp_unity_narrative',
    name: '兩岸一家親宣傳',
    category: '認知',
    cost: 1,
    desc: '強化「血濃於水」論述，模糊台灣主體意識',
    flavor: '文化認同是比飛彈更隱性的戰場',
    effects: { propaganda: 7 },
    sideEffects: { tw_morale: -8, tw_softpower: -4 },
  },
  {
    id: 'ccp_social_media_bots',
    name: '社群機器人軍團',
    category: '認知',
    cost: 1,
    desc: '數千個假帳號放大社會矛盾',
    flavor: '演算法是最好的武器',
    effects: { propaganda: 8, infiltration: 4 },
    sideEffects: { tw_morale: -8 },
  },
  {
    id: 'ccp_electoral_interference',
    name: '選舉干預',
    category: '認知',
    cost: 3,
    desc: '在台灣選舉期間大規模介入，影響選舉結果',
    flavor: '民主制度的漏洞就是開放',
    effects: { propaganda: 14, infiltration: 10 },
    sideEffects: { tw_morale: -15, tension: 8 },
    cooldown: 4,
    triggersTW: 'tw_disinfo_immunity',
  },

  // ──────────────────────────────────────────────
  // 類別：經濟施壓
  // ──────────────────────────────────────────────
  {
    id: 'ccp_economic_coerce',
    name: '農漁產品禁令',
    category: '經濟',
    cost: 1,
    desc: '禁止台灣農漁業產品進口，打擊特定選區',
    flavor: '釋迦鳳梨先走，下一個是誰？',
    effects: { economy: 6 },
    sideEffects: { tw_economy: -8, tw_morale: -5 },
  },
  {
    id: 'ccp_rare_earth_threat',
    name: '稀土禁令威脅',
    category: '經濟',
    cost: 2,
    desc: '以稀土出口管制威脅半導體供應鏈',
    flavor: '你有晶片，我有材料',
    effects: { economy: 8 },
    sideEffects: { tw_chip: -10, tw_economy: -6 },
    triggersTW: 'tw_supply_chain_reorg',
  },
  {
    id: 'ccp_tourism_cutoff',
    name: '陸客斷流',
    category: '經濟',
    cost: 1,
    desc: '禁止中國大陸民眾赴台旅遊',
    flavor: '觀光客變成了政治武器',
    effects: { economy: 4 },
    sideEffects: { tw_economy: -6 },
  },
  {
    id: 'ccp_financial_attack',
    name: '金融市場攻擊',
    category: '經濟',
    cost: 2,
    desc: '透過衍生品操作衝擊台股與新台幣',
    flavor: '金融戰不留彈孔',
    effects: { economy: 8, tension: 5 },
    sideEffects: { tw_economy: -12, tw_morale: -6 },
    cooldown: 3,
  },
  {
    id: 'ccp_investment_lure',
    name: '惠台投資誘因',
    category: '經濟',
    cost: 1,
    desc: '以優惠政策吸引台灣企業與人才外流',
    flavor: '搶人才比搶領土更有效率',
    effects: { economy: 5, infiltration: 5 },
    sideEffects: { tw_economy: -5, tw_chip: -4 },
  },
  {
    id: 'ccp_trade_war',
    name: '全面貿易戰',
    category: '經濟',
    cost: 3,
    desc: '對台灣發動全面貿易制裁',
    flavor: '代價是雙向的——但誰撐得住？',
    effects: { economy: 10, tension: 8 },
    sideEffects: { tw_economy: -15, economy: -6 },
    cooldown: 3,
    triggersTW: 'tw_friendshore',
  },

  // ──────────────────────────────────────────────
  // 類別：外交絞殺
  // ──────────────────────────────────────────────
  {
    id: 'ccp_diplomatic_isolate',
    name: '挖角邦交國',
    category: '外交',
    cost: 2,
    desc: '以金錢利誘台灣邦交國轉向承認北京',
    flavor: '每失去一個邦交國就少一張選票',
    effects: { diplomacy: 8 },
    sideEffects: { tw_diplomacy: -10, tw_morale: -5 },
  },
  {
    id: 'ccp_who_block',
    name: '封鎖WHO參與',
    category: '外交',
    cost: 1,
    desc: '阻擋台灣以任何名義參與世界衛生大會',
    flavor: '連健康都成了政治籌碼',
    effects: { diplomacy: 5 },
    sideEffects: { tw_diplomacy: -7, tw_softpower: -5 },
  },
  {
    id: 'ccp_un_resolution',
    name: '聯合國決議施壓',
    category: '外交',
    cost: 2,
    desc: '推動台灣問題相關決議，強化一中框架',
    flavor: '多數決可以製造合法性幻覺',
    effects: { diplomacy: 10 },
    sideEffects: { tw_diplomacy: -8 },
    cooldown: 2,
  },
  {
    id: 'ccp_bri_leverage',
    name: '一帶一路槓桿',
    category: '外交',
    cost: 2,
    desc: '以BRI國家為票倉，在國際組織圍堵台灣',
    flavor: '債務陷阱換來的是選票',
    effects: { diplomacy: 12 },
    sideEffects: { tw_diplomacy: -10 },
  },
  {
    id: 'ccp_russia_axis',
    name: '中俄軸心強化',
    category: '外交',
    cost: 2,
    desc: '與俄羅斯深化安全合作，分散美國注意力',
    flavor: '當歐洲在燃燒，亞洲的防線就薄了',
    effects: { diplomacy: 8, military: 5, tension: 6 },
    sideEffects: { tw_diplomacy: -6 },
  },
  {
    id: 'ccp_global_south',
    name: '全球南方籠絡',
    category: '外交',
    cost: 1,
    desc: '以發展援助換取全球南方國家在台灣問題上的沉默',
    flavor: '不需要支持，只需要不反對',
    effects: { diplomacy: 7 },
    sideEffects: { tw_diplomacy: -5 },
  },

  // ──────────────────────────────────────────────
  // 類別：網路攻擊
  // ──────────────────────────────────────────────
  {
    id: 'ccp_cyber_infra',
    name: '關鍵設施駭入',
    category: '網路',
    cost: 2,
    desc: '攻擊電力、水利、通訊等關鍵基礎設施',
    flavor: '不發一槍，燈就滅了',
    effects: { cyber: 10, tension: 6 },
    sideEffects: { tw_resilience: -10, tw_morale: -8, tw_economy: -5 },
    cooldown: 2,
  },
  {
    id: 'ccp_cyber_military',
    name: '軍事網路入侵',
    category: '網路',
    cost: 2,
    desc: '入侵台灣軍事通訊系統，竊取作戰計畫',
    flavor: '知己知彼，百戰不殆——反過來說也成立',
    effects: { cyber: 12, intel: 8 },
    sideEffects: { tw_intel: -12, tw_military: -5 },
    cooldown: 2,
    triggersTW: 'tw_cyber_defense',
  },
  {
    id: 'ccp_supply_chain_hack',
    name: '供應鏈軟體攻擊',
    category: '網路',
    cost: 2,
    desc: 'SolarWinds式攻擊植入後門，長期潛伏',
    flavor: '最好的入侵讓你三年後才發現',
    effects: { cyber: 12, infiltration: 6 },
    sideEffects: { tw_chip: -6, tw_intel: -8 },
  },
  {
    id: 'ccp_undersea_cable',
    name: '海底電纜破壞',
    category: '網路',
    cost: 2,
    desc: '切斷台灣對外海底通訊電纜',
    flavor: '資訊孤島比地理孤島更難突破',
    effects: { cyber: 10, tension: 8 },
    sideEffects: { tw_economy: -8, tw_intel: -10, tw_morale: -6 },
    cooldown: 3,
  },
  {
    id: 'ccp_ddos',
    name: 'DDoS癱瘓攻擊',
    category: '網路',
    cost: 1,
    desc: '對台灣政府與金融網站發動大規模DDoS',
    flavor: '打不死你，但讓你癱在那裡',
    effects: { cyber: 7 },
    sideEffects: { tw_resilience: -6, tw_economy: -4 },
  },

  // ──────────────────────────────────────────────
  // 類別：灰色地帶
  // ──────────────────────────────────────────────
  {
    id: 'ccp_fishing_militia',
    name: '漁船民兵',
    category: '灰色地帶',
    cost: 1,
    desc: '漁船偽裝的海上民兵在台灣周邊騷擾',
    flavor: '不是軍艦，你能怎麼辦？',
    effects: { tension: 6, military: 4 },
    sideEffects: { tw_morale: -5, tw_economy: -3 },
  },
  {
    id: 'ccp_balloon_recon',
    name: '氣球偵察',
    category: '灰色地帶',
    cost: 1,
    desc: '高空氣球蒐集台灣軍事設施情報',
    flavor: '不算飛機，不算導彈，難以擊落',
    effects: { intel: 8, tension: 4 },
    sideEffects: { tw_intel: -5 },
  },
  {
    id: 'ccp_sand_island',
    name: '沙洲島礁建設',
    category: '灰色地帶',
    cost: 2,
    desc: '在爭議海域建設軍事化島礁',
    flavor: '主權是慢慢吃掉的',
    effects: { military: 7, tension: 7 },
    sideEffects: { tw_diplomacy: -5, tw_morale: -4 },
  },
  {
    id: 'ccp_salami_slice',
    name: '切香腸戰術',
    category: '灰色地帶',
    cost: 1,
    desc: '一次一小步蠶食，讓每步都不值得強烈反應',
    flavor: '溫水煮青蛙是最有效的方法',
    effects: { tension: 5, infiltration: 5 },
    sideEffects: { tw_morale: -6, tw_diplomacy: -4 },
  },
  {
    id: 'ccp_coast_guard',
    name: '海警船騷擾',
    category: '灰色地帶',
    cost: 1,
    desc: '海警船進入台灣主張海域，測試底線',
    flavor: '不是海軍，法律就不一樣',
    effects: { tension: 7, military: 3 },
    sideEffects: { tw_morale: -5 },
  },
];

// 依類別索引
const CCP_CARDS_BY_CATEGORY = CCP_CARDS.reduce((acc, card) => {
  if (!acc[card.category]) acc[card.category] = [];
  acc[card.category].push(card);
  return acc;
}, {});
