// ============================================================
// cards_taiwan.js — 臺灣陣營卡牌資料庫
// 每張牌結構：
//   id, name, category, cost(AP), desc, flavor,
//   effects: { stat: delta, ... }
//   sideEffects: { stat: delta, ... }  (可選)
//   unlockRequires: [ card_id, ... ]   (可選)
//   triggersCCP: card_id               (可選，觸發中共反應牌)
//   cooldown: N                        (可選，N季後才能再用)
// ============================================================

const TAIWAN_CARDS = [

  // ──────────────────────────────────────────────
  // 類別：軍事硬實力
  // ──────────────────────────────────────────────
  {
    id: 'tw_asymmetric_warfare',
    name: '不對稱作戰',
    category: '軍事',
    cost: 2,
    desc: '部署刺蝟戰略，以小搏大阻絕登陸',
    flavor: '「讓入侵者付出難以承受的代價」',
    effects: { military: 12, morale: 4 },
    triggersCCP: 'ccp_mil_exercise',
  },
  {
    id: 'tw_drone_fleet',
    name: '無人機艦隊',
    category: '軍事',
    cost: 2,
    desc: '自製量產無人機，強化海空監控與打擊能力',
    flavor: '烏俄戰爭的教訓：成本不對稱才是優勢',
    effects: { military: 10, intel: 6 },
    cooldown: 2,
  },
  {
    id: 'tw_mine_barrier',
    name: '水雷防線',
    category: '軍事',
    cost: 1,
    desc: '在重要海峽佈設智慧水雷，阻止兩棲登陸',
    flavor: '最便宜的嚇阻手段之一',
    effects: { military: 8 },
    sideEffects: { diplomacy: -3 },
  },
  {
    id: 'tw_civil_defense',
    name: '全民國防教育',
    category: '軍事',
    cost: 1,
    desc: '強化後備動員與民間防衛訓練',
    flavor: '每個公民都是守土的一部分',
    effects: { military: 6, morale: 8, resilience: 5 },
  },
  {
    id: 'tw_missile_defense',
    name: '飛彈防禦網',
    category: '軍事',
    cost: 3,
    desc: '建立多層次防空反飛彈系統',
    flavor: '天劍、愛國者、天弓——三層盾牌',
    effects: { military: 14, morale: 6 },
    cooldown: 3,
    triggersCCP: 'ccp_blockade_drill',
  },
  {
    id: 'tw_submarine',
    name: '自製潛艦',
    category: '軍事',
    cost: 3,
    desc: '海鯤號量產計畫，強化水下打擊力',
    flavor: '看不見的牙齒才是最危險的',
    effects: { military: 15 },
    sideEffects: { economy: -5 },
    cooldown: 3,
  },
  {
    id: 'tw_reserve_reform',
    name: '後備改革',
    category: '軍事',
    cost: 1,
    desc: '延長後備訓練、提升戰力留存',
    flavor: '數量不夠，品質來補',
    effects: { military: 7, morale: 5 },
  },
  {
    id: 'tw_coastal_defense',
    name: '岸置反艦飛彈',
    category: '軍事',
    cost: 2,
    desc: '雄二E岸射型大量部署',
    flavor: '讓每艘靠近的軍艦都知道代價',
    effects: { military: 10 },
    triggersCCP: 'ccp_mil_exercise',
  },
  {
    id: 'tw_cyber_defense',
    name: '資安防禦強化',
    category: '軍事',
    cost: 1,
    desc: '建立國家級資安中心，防範關鍵基礎設施攻擊',
    flavor: '第五維度的戰場',
    effects: { intel: 10, resilience: 8 },
  },
  {
    id: 'tw_special_forces',
    name: '特種部隊擴編',
    category: '軍事',
    cost: 2,
    desc: '雷霆、海龍部隊擴充，強化突擊能力',
    flavor: '不對稱戰力的尖刀',
    effects: { military: 9, intel: 4 },
  },

  // ──────────────────────────────────────────────
  // 類別：晶片科技
  // ──────────────────────────────────────────────
  {
    id: 'tw_tsmc_shield',
    name: '矽盾強化',
    category: '科技',
    cost: 2,
    desc: '臺積電擴大先進製程優勢，讓全球依賴深化',
    flavor: '你打我，全球供應鏈就斷了',
    effects: { chip: 10, economy: 6, diplomacy: 5 },
    triggersCCP: 'ccp_economic_coerce',
  },
  {
    id: 'tw_chip_diplomacy',
    name: '晶片外交',
    category: '科技',
    cost: 2,
    desc: '以先進晶片供應換取盟友政治支持',
    flavor: '半導體就是二十一世紀的石油',
    effects: { diplomacy: 12, chip: 4, economy: 5 },
  },
  {
    id: 'tw_chip_diversify',
    name: '晶片廠分散佈局',
    category: '科技',
    cost: 2,
    desc: '在日本、美國、德國設廠，降低單點風險',
    flavor: '雞蛋不放同一個籃子',
    effects: { chip: 6, diplomacy: 8 },
    sideEffects: { economy: -4 },
    cooldown: 2,
  },
  {
    id: 'tw_ai_chip',
    name: 'AI晶片研發',
    category: '科技',
    cost: 3,
    desc: '投資下世代AI專用晶片，維持技術領先',
    flavor: 'Nvidia只能設計，我們才能製造',
    effects: { chip: 14, economy: 8 },
    cooldown: 3,
  },
  {
    id: 'tw_export_control',
    name: '晶片出口管制',
    category: '科技',
    cost: 1,
    desc: '配合美國限制中共取得先進晶片',
    flavor: '技術封鎖就是戰略圍堵',
    effects: { chip: 5, diplomacy: 7 },
    sideEffects: { economy: -3 },
    triggersCCP: 'ccp_economic_coerce',
  },
  {
    id: 'tw_quantum_research',
    name: '量子科技投資',
    category: '科技',
    cost: 2,
    desc: '量子通訊與運算，打造未來加密優勢',
    flavor: '下一代的技術戰場',
    effects: { chip: 8, intel: 8 },
    cooldown: 2,
  },
  {
    id: 'tw_space_program',
    name: '太空計畫',
    category: '科技',
    cost: 2,
    desc: '自主衛星偵察與通訊系統',
    flavor: 'Starlink的教訓：衛星就是戰略資產',
    effects: { intel: 12, military: 5 },
    cooldown: 3,
  },
  {
    id: 'tw_5g_security',
    name: '5G安全網路',
    category: '科技',
    cost: 1,
    desc: '建立去中化5G基礎設施，排除華為設備',
    flavor: '通訊安全等於國家安全',
    effects: { intel: 7, resilience: 6 },
  },

  // ──────────────────────────────────────────────
  // 類別：外交
  // ──────────────────────────────────────────────
  {
    id: 'tw_us_alliance',
    name: '深化美台關係',
    category: '外交',
    cost: 2,
    desc: '推動《台灣關係法》升級，獲得更明確安全承諾',
    flavor: '戰略模糊正在轉向戰略清晰',
    effects: { diplomacy: 14, military: 6 },
    triggersCCP: 'ccp_diplomatic_isolate',
    cooldown: 2,
  },
  {
    id: 'tw_japan_partnership',
    name: '日台安全夥伴',
    category: '外交',
    cost: 2,
    desc: '強化與日本的非正式安全合作',
    flavor: '台灣有事就是日本有事',
    effects: { diplomacy: 10, military: 5 },
  },
  {
    id: 'tw_indo_pacific',
    name: '印太框架參與',
    category: '外交',
    cost: 1,
    desc: '積極參與IPEF與Quad相關活動',
    flavor: '找到志同道合的民主陣營',
    effects: { diplomacy: 8, economy: 5 },
  },
  {
    id: 'tw_eu_relations',
    name: '歐盟深化關係',
    category: '外交',
    cost: 1,
    desc: '推動台歐投資協議與政治對話',
    flavor: '多元化不依賴單一保護者',
    effects: { diplomacy: 9, economy: 6 },
  },
  {
    id: 'tw_congressmen_visit',
    name: '外國議員訪台',
    category: '外交',
    cost: 1,
    desc: '邀請各國議員訪台，強化民主連結',
    flavor: '每一次訪問都是政治表態',
    effects: { diplomacy: 7, morale: 5 },
    triggersCCP: 'ccp_mil_exercise',
  },
  {
    id: 'tw_who_participation',
    name: '世衛組織參與',
    category: '外交',
    cost: 1,
    desc: '爭取以觀察員身分出席WHO大會',
    flavor: '健康不應有政治邊界',
    effects: { diplomacy: 8, morale: 6 },
    triggersCCP: 'ccp_diplomatic_isolate',
  },
  {
    id: 'tw_nato_dialogue',
    name: 'NATO對話機制',
    category: '外交',
    cost: 2,
    desc: '以非正式管道建立與北約的安全對話',
    flavor: '民主價值是最堅固的同盟基礎',
    effects: { diplomacy: 11, military: 4 },
    cooldown: 2,
  },
  {
    id: 'tw_pacific_allies',
    name: '太平洋邦交鞏固',
    category: '外交',
    cost: 1,
    desc: '強化與帛琉、馬紹爾等邦交國關係',
    flavor: '小島嶼大意義',
    effects: { diplomacy: 6 },
    sideEffects: { economy: -2 },
  },
  {
    id: 'tw_diaspora_network',
    name: '海外僑民網路',
    category: '外交',
    cost: 1,
    desc: '活化全球台僑社群，形成軟實力節點',
    flavor: '每個海外台灣人都是大使',
    effects: { diplomacy: 6, morale: 5, softpower: 4 },
  },

  // ──────────────────────────────────────────────
  // 類別：社會韌性
  // ──────────────────────────────────────────────
  {
    id: 'tw_disinfo_immunity',
    name: '假訊息免疫計畫',
    category: '社會',
    cost: 1,
    desc: '全民媒體識讀教育，對抗認知作戰',
    flavor: 'COFACTS事實查核——公民的第一道防線',
    effects: { resilience: 10, morale: 6 },
  },
  {
    id: 'tw_energy_independence',
    name: '能源自主',
    category: '社會',
    cost: 2,
    desc: '加速再生能源建設，降低能源被掐斷的風險',
    flavor: '能源自主才有真正的國家自主',
    effects: { resilience: 10, economy: 5 },
    cooldown: 2,
  },
  {
    id: 'tw_food_security',
    name: '糧食安全儲備',
    category: '社會',
    cost: 1,
    desc: '建立戰略糧食儲備與在地農業強化',
    flavor: '封鎖戰的關鍵不只是軍事',
    effects: { resilience: 8, morale: 4 },
  },
  {
    id: 'tw_underground_infra',
    name: '地下化關鍵設施',
    category: '社會',
    cost: 2,
    desc: '電力、通訊、水利設施地下化',
    flavor: '炸不到才是真正的韌性',
    effects: { resilience: 12, military: 3 },
    sideEffects: { economy: -4 },
    cooldown: 3,
  },
  {
    id: 'tw_mental_resilience',
    name: '心理韌性強化',
    category: '社會',
    cost: 1,
    desc: '對抗恐懼、強化民心，打接觸戰前先打心理戰',
    flavor: '烏克蘭人教我們：士氣是最強的武器',
    effects: { morale: 12, resilience: 5 },
  },
  {
    id: 'tw_local_supply_chain',
    name: '在地供應鏈韌性',
    category: '社會',
    cost: 1,
    desc: '降低關鍵物資對外依賴，強化本土製造',
    flavor: '口罩事件的教訓',
    effects: { resilience: 7, economy: 4 },
  },

  // ──────────────────────────────────────────────
  // 類別：軟實力
  // ──────────────────────────────────────────────
  {
    id: 'tw_mask_diplomacy',
    name: '口罩外交',
    category: '軟實力',
    cost: 1,
    desc: '防疫物資輸出，建立國際善意與知名度',
    flavor: '「Taiwan Can Help」讓世界看到台灣',
    effects: { diplomacy: 8, softpower: 10, morale: 5 },
  },
  {
    id: 'tw_intl_students',
    name: '留學生外交',
    category: '軟實力',
    cost: 1,
    desc: '吸引各國留學生來台，深化人際連結',
    flavor: '每個留學生回國後都是台灣的朋友',
    effects: { softpower: 8, diplomacy: 6 },
  },
  {
    id: 'tw_culture_export',
    name: '文化輸出',
    category: '軟實力',
    cost: 1,
    desc: '台灣電影、音樂、美食走向國際',
    flavor: '珍珠奶茶比任何廣告都有效',
    effects: { softpower: 9, morale: 5 },
  },
  {
    id: 'tw_ngo_diplomacy',
    name: 'NGO外交',
    category: '軟實力',
    cost: 1,
    desc: '台灣NGO深耕東南亞非洲，建立草根影響力',
    flavor: '看不見的外交才是最長久的',
    effects: { softpower: 7, diplomacy: 5 },
  },
  {
    id: 'tw_democracy_export',
    name: '民主典範輸出',
    category: '軟實力',
    cost: 1,
    desc: '分享台灣民主轉型經驗，提升國際道德高地',
    flavor: '台灣是華人世界最好的反例',
    effects: { softpower: 8, diplomacy: 7, morale: 5 },
  },
  {
    id: 'tw_intl_media',
    name: '國際媒體佈局',
    category: '軟實力',
    cost: 2,
    desc: '投資英語媒體平台，對抗中共敘事壟斷',
    flavor: '話語權決定誰的故事被聽見',
    effects: { softpower: 11, resilience: 5 },
    cooldown: 2,
  },

  // ──────────────────────────────────────────────
  // 類別：經濟
  // ──────────────────────────────────────────────
  {
    id: 'tw_supply_chain_reorg',
    name: '供應鏈重組',
    category: '經濟',
    cost: 2,
    desc: '推動製造業回台與友岸外包，降低對中依賴',
    flavor: '去風險化不是脫鉤，是分散',
    effects: { economy: 10, resilience: 7 },
    sideEffects: { diplomacy: -2 },
  },
  {
    id: 'tw_friendshore',
    name: '友岸外包策略',
    category: '經濟',
    cost: 1,
    desc: '與民主盟友共建供應鏈，排除威權風險',
    flavor: '把供應鏈變成地緣政治工具',
    effects: { economy: 8, diplomacy: 5 },
  },
  {
    id: 'tw_tourism_push',
    name: '觀光振興',
    category: '經濟',
    cost: 1,
    desc: '吸引國際觀光客，強化民間外交與收入',
    flavor: '讓人們親眼看見台灣的美',
    effects: { economy: 7, softpower: 5, morale: 4 },
  },
  {
    id: 'tw_startup_ecosystem',
    name: '新創生態系',
    category: '經濟',
    cost: 1,
    desc: '強化台灣科技新創，培育下一個護國神山',
    flavor: '半導體之後，接下來是什麼？',
    effects: { economy: 8, chip: 4 },
  },
  {
    id: 'tw_financial_resilience',
    name: '金融韌性強化',
    category: '經濟',
    cost: 1,
    desc: '對抗可能的金融攻擊與外匯衝擊',
    flavor: '戰爭的第一戰場往往是金融',
    effects: { economy: 6, resilience: 8 },
  },

  // ──────────────────────────────────────────────
  // 類別：情報
  // ──────────────────────────────────────────────
  {
    id: 'tw_counter_intel',
    name: '反情報行動',
    category: '情報',
    cost: 1,
    desc: '清查中共滲透網絡，逮捕間諜',
    flavor: '內部乾淨才能對外強硬',
    effects: { intel: 10, resilience: 5 },
    special: 'counter_infiltration',
  },
  {
    id: 'tw_signal_intel',
    name: '電子訊號情報',
    category: '情報',
    cost: 2,
    desc: '強化對解放軍通訊的監聽與分析',
    flavor: '知道敵人下一步才能預先防範',
    effects: { intel: 12, military: 5 },
    cooldown: 2,
  },
  {
    id: 'tw_human_intel',
    name: '人力情報網',
    category: '情報',
    cost: 2,
    desc: '在中國大陸建立情報線人網絡',
    flavor: '最難複製的優勢：知情者的信任',
    effects: { intel: 14 },
    sideEffects: { diplomacy: -3 },
    cooldown: 2,
  },
  {
    id: 'tw_five_eyes_share',
    name: '五眼聯盟情報共享',
    category: '情報',
    cost: 1,
    desc: '與美英澳加紐情報共享，強化戰略預警',
    flavor: '情報是同盟最核心的紐帶',
    effects: { intel: 10, diplomacy: 5 },
  },
];

// 依類別索引
const TAIWAN_CARDS_BY_CATEGORY = TAIWAN_CARDS.reduce((acc, card) => {
  if (!acc[card.category]) acc[card.category] = [];
  acc[card.category].push(card);
  return acc;
}, {});
